### ISSUE TITLE
Another completely noob question ...

### ISSUE THREAD

**Issue by derekisastro** [MindFreeze/dalybms#2]
Does this add-on rely on connecting the UART output directly to a USB input of the Raspberry Pi (or another device) that I am running my HA instance on?

If not, what is the UART output cable actually connected to ... another Pi device?

**Comment by MindFreeze** [comment]
Yes, this assumes that you have connected HA to the BMS with the USB-UART cable. 
Alternatively you can just take monitor.py, see how to set the env variables from run.sh and excute the python script on another pi connected to the BMS.

How I actually use it is, I have an extra raspberry pi running a barebones instance of HA, connected to the BMS UART, and I run the addon on that. This allows me to use it as a HA addon, with backups, updates, etc. without running a cable to my main HA server but the data is actually sent to my main HA's mqtt server. I also have other addons running this way that connect to my inverters.

**Comment by derekisastro** [comment]
Thank you for the quick response. The way you use it is the way I want to utilize the add-on. My HA server and my BMS/battery are too far apart to be directly connected.

**Comment by MindFreeze** [comment]
It can be extended to set settings as well but currently it only supports monitoring. 

I don't plan on adding settings because I don't need to change anything after initial setup. And if I do need to change settings, I can plug in the Bluetooth dongle on the BMS and configure it through the official app.

**Comment by derekisastro** [comment]
That makes sense. Thank you.
