### ISSUE TITLE
Expanding functionality

### ISSUE THREAD

**Issue by DoctorMarshall** [MindFreeze/dalybms#3]
Hi,

would be awesome if temperature, alarms, and mosfets (as mentioned) were added.
Thanks!

**Comment by DoctorMarshall** [comment]
Sweet, thanks! 

I was thinking of alarms that appear in the BMS app when temp/cell voltage/cell difference etc is reached.
But this can be done in the assistant based on the values so probably does not make sense to implement it.

Awesome addon, thanks for your work <3

**Comment by MindFreeze** [comment]
Yeah, I probably won't bother with alarms or settings.

The temperature is a bit weird. The protocol seems to be set up for individual sensors for each cell but my BMSs only have 1 sensor. I created a temperature sensor in HA with min and max in the attributes, which are the same for me. 
There is another temp value that is always reported as 1 on my boards. I put that in the attributes of the state of charge sensor in case it works for someone else.

**Comment by Zippa1204** [comment]
Hi,

I am getting this error when I try to start it on Home Assistant:

s6-overlay-suexec: fatal: can only run as pid 1

Gert

**Comment by MindFreeze** [comment]
@Zippa1204 Try the latest version. If it doesn't work, open a new issue. This is not the place for discussing it.

**Comment by renenemecek** [comment]
> I just added temperature. MOSFETs will come soon.
> 
> But what do you mean by alarms? The overcharge and overdischarge voltage range?

Hi, are you going to solve the mosfet status sometime ?

**Comment by MindFreeze** [comment]
@renenemecek added mosfets in 1.5.0
They are added as attributes with 0 or 1 state though
