### ISSUE TITLE
DalyBMS

### ISSUE THREAD

**Issue by Zippa1204** [MindFreeze/dalybms#4]
Hi,

I am getting this error when I try to start it on Home Assistant:

s6-overlay-suexec: fatal: can only run as pid 1

Gert

**Comment by Zippa1204** [comment]
Hello,

After update, the s6 error is fixed - THANK YOU.

I note that you did mention it works for /dev/ttyUSB0, hoewever when I connect mt USB, it starts at USB1.

If I change it in the configuration page, I get a permission error:
PermissionError: [Errno 1] Operation not permitted: '/dev/ttyUSB1'

Gert

**Comment by MindFreeze** [comment]
This is a limitation in HA addons. If you want to use /dev/ttyUSB1 , you have to either fork the repo and change it in `config.json` or just copy this addon your local `addons` directory in HA (through SSH or similar) and edit config.json there.
