### ISSUE TITLE
HA installation problem

### ISSUE THREAD

**Issue by spacecodes1** [MindFreeze/dalybms#6]
Hi,

Have an issue while attempting to install on HA :
"The command '/bin/ash -o pipefail -c apk add --no-cache python3 && python3 -m ensurepip && rm -r /usr/lib/python*/ensurepip && python3 -m pip install -r requirements.txt && rm -r /root/.cache' returned a non-zero code: 1"

Home Assistant 2023.8.2
Supervisor 2023.08.1
Operating System 10.4
Interface utilisateur : 20230802.0 - latest
Raspberry Pi 4 4GB

**Comment by Chiripasca** [comment]
Hola
Tengo el mismo problema. ¿pudiste solucionarlo?
